Update patch set 1
Patch Set 1:

I get this error while trying to compile android on my Fedora 13 machine. Having this patch fixes this issue. I was not sure if Ubuntu (which does not see this issue) implicitly adds this dependency?


host Executable: emulator_renderer (out/host/linux-x86/obj/EXECUTABLES/emulator_renderer_intermediates/emulator_renderer)
/usr/bin/ld: out/host/linux-x86/obj/EXECUTABLES/emulator_renderer_intermediates/main.o: undefined reference to symbol 'XInitThreads'
/usr/bin/ld: note: 'XInitThreads' is defined in DSO /usr/lib/libX11.so.6 so try adding it to the linker command line
/usr/lib/libX11.so.6: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make: *** [out/host/linux-x86/obj/EXECUTABLES/emulator_renderer_intermediates/emulator_renderer] Error 1
make: Leaving directory `/data/wip-mips-ics-mr1.1_TEST'


Sorry the description was kind of intentionally vague, because I could not confirm its failure on other types of Linux. I can edit it if you prefer.

Patch-set: 1
Label: Code-Review=0