Update patch set 3
Patch Set 3: Fails

Unfortunately, this still breaks the Mac build. Please test on all platforms before submitting.

host C++: triangleCM <= development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp
In file included from <command line>:1:
./system/core/include/arch/darwin-x86/AndroidConfig.h:190:1: warning: "_THREAD_SAFE" redefined
<command line>:1:1: warning: this is the location of the previous definition
In file included from frameworks/base/opengl/include/EGL/egl.h:36,
                 from development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:10:
frameworks/base/opengl/include/EGL/eglplatform.h:102:2: error: #error "Platform not recognized"
frameworks/base/opengl/include/EGL/eglplatform.h:106: error: 'EGLNativeDisplayType' does not name a type
frameworks/base/opengl/include/EGL/eglplatform.h:107: error: 'EGLNativePixmapType' does not name a type
frameworks/base/opengl/include/EGL/eglplatform.h:108: error: 'EGLNativeWindowType' does not name a type
frameworks/base/opengl/include/EGL/egl.h:251: error: 'EGLNativeDisplayType' was not declared in this scope
frameworks/base/opengl/include/EGL/egl.h:266: error: 'EGLNativeWindowType' has not been declared
frameworks/base/opengl/include/EGL/egl.h:271: error: 'EGLNativePixmapType' has not been declared
frameworks/base/opengl/include/EGL/egl.h:314: error: 'EGLNativePixmapType' has not been declared
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp: In function 'int SDL_main(int, char**)':
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:124: error: 'Window' was not declared in this scope
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:124: error: expected `;' before 'windowId'
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:146: error: 'windowId' was not declared in this scope
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:146: error: 'struct SDL_SysWMinfo' has no member named 'info'
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:153: error: 'EGLNativeDisplayType' was not declared in this scope
development/tools/emulator/opengl/tests/translator_tests/GLES_CM/triangleCM.cpp:153: error: expected `)' before numeric constant
make: *** [out/host/darwin-x86/obj/EXECUTABLES/triangleCM_intermediates/triangleCM.o] Error 1
make: *** Waiting for unfinished jobs....

Patch-set: 3
Label: Code-Review=0
Label: Verified=-1