Update patch set 1
Patch Set 1:

(1 comment)

> This is a cool idea, it makes the Python code way cleaner! I'm
 > testing it on Windows 7 though and this seems to break
 > test_unicode_paths for me:
 > 
 > ShellError: `['ls', '/data/local/tmp/adb-test-*']` exited with code
 > 1
 > 
 > My USB drivers seem to be misbehaving at the moment so possibly my
 > computer is messed up, but it is just this one test that's failing
 > consistently. Is this test passing for you?

Yeah, that test passes for me. I'm on Win10 x64 + Python x64.

What is funny is that the line that is failing has no Unicode python strings, so it shouldn't even invoke PowerShell.

Maybe you're running a newer Android that has locked down /data/local/tmp more?

Patch-set: 1